### ISSUE TITLE
Sync the wiki with a directory in the repository

### ISSUE THREAD

**Issue by Metacinnabar** [uranometrical/notes#1]
Something like [this](https://github.com/marketplace/actions/publish-to-github-wiki).

Why?
Easy to archive, easy to copy, etc etc I can't think of more points.

**Comment by steviegt6** [comment]
https://github.com/uranometrical/notes.wiki.git
Wikis already have their own repository.

**Comment by steviegt6** [comment]
On second thought, sure.
