### ISSUE TITLE
[SUGGESTION] Move to MediaWIki

### ISSUE THREAD

**Issue by steviegt6** [uranometrical/notes#3]
I firmly believe that contributions and moderation would be significantly easier to I were to move uranometrical/notes to (a potential fork of) MediaWiki.

Localization and maintaining the wiki itself would become significantly easier, and a familiar environment would be more user-friendly.

**Comment by steviegt6** [comment]
@Metacinnabar

**Comment by Metacinnabar** [comment]
Looks promising, I would prefer if we found a nice looking theme however.
